eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://cdms-eureka-server:8761/eureka
    # instance:
      # hostname: localhost

server:
  port: 8080

spring:
  application:
    name: cdms-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: cdms-usuarios
        uri: lb://cdms-usuarios
        predicates:
        - Path=/api/v1/auth/refresh, /api/v1/auth/register, /api/v1/auth/login, /api/v1/auth/validate
      - id: cdms-estaciones
        uri: lb://cdms-estaciones
        predicates:
        - Path=/api/v1/estaciones/**, /api/v1/sensores/**, /api/v1/calibraciones/**, /api/v1/unidades-medida/**, /api/v1/mantenimientos/estacion/**, /api/v1/imagenes/**, /api/v1/ubicaciones-estacion/**, /api/v1/contactos-estacion/**
        filters:
        - AuthFilter
      - id: cdms-obervaciones
        uri: lb://cdms-observaciones
        predicates:
        - Path=/api/v1/observaciones/upload,/api/v1/observaciones/resumen/**,/api/v1/observaciones/noaa/**,/api/v1/observaciones/variable/**
        filters:
        - AuthFilter
      - id: cdms-mantenimiento
        uri: lb://cdms-mantenimiento
        predicates:
        - Path=/api/v1/mantenimientos/**, /api/v1/accesorios/**, /api/v1/inventario-repuestos/**, /api/v1/documentos-anexos/**
        filters:
          - AuthFilter