server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: cdms-obs

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://cdms-eureka-server:8761/eureka
    instance:
      preferIpAddress: true