server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: cdms-observaciones

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhos:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}